/**终端列表状态*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('zhuangtai',NULL,NULL,'0',NULL,'0','zhuangtai','终端列表状态',NULL,'终端列表状态',1,1,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zhuangtai001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'zhuangtai001', '启用', 1, '启用', NULL, '0', 'zhuangtai001', 0, 0, '', 'zhuangtai', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zhuangtai002', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'zhuangtai002', '停用', 1, '停用', NULL, '0', 'zhuangtai002', 0, 0, '', 'zhuangtai', NULL);

/**终端类别*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('zdlb',NULL,NULL,'0',NULL,'0','zdlb','终端类别',NULL,'终端类别',1,1,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zdlb001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'zdlb001', '终端类别', 1, '终端类别', NULL, '0', 'zdlb001', 0, 0, '', 'zdlb', NULL);
/**终端状态*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('zdzt',NULL,NULL,'0',NULL,'0','zdzt','终端状态',NULL,'终端状态',1,1,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zdzt001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'zdzt001', '终端状态', 1, '终端状态', NULL, '0', 'zdzt001', 0, 0, '', 'zdzt', NULL);
/**终端归属*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('zdgs',NULL,NULL,'0',NULL,'0','zdgs','终端归属',NULL,'终端归属',1,1,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zdgs001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'zdgs001', '终端归属', 1, '终端归属', NULL, '0', 'zdgs001', 0, 0, '', 'zdgs', NULL);
/**是否机构公用*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('gggy',NULL,NULL,'0',NULL,'0','gggy','是否机构公用',NULL,'是否机构公用',1,1,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'gggy001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'gggy001', '机构公用', 1, '机构公用', NULL, '0', 'gggy001', 0, 0, '', 'gggy', NULL);
/**返佣类型*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('fylx',NULL,NULL,'0',NULL,'0','fylx','返佣类型',NULL,'返佣类型',1,1,0,NULL,NULL,NULL,NULL,NULL);

INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'fylx001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'fylx001', '返佣比例', 1, '返佣比例', NULL, '0', 'fylx001', 0, 0, '', 'fylx', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'fylx002', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'fylx002', '返佣金额', 1, '返佣金额', NULL, '0', 'fylx002', 0, 0, '', 'fylx', NULL);
/**是和否*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('yorn',NULL,NULL,'0',NULL,'0','yorn','是和否',NULL,'是和否',1,1,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'yorn001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'yorn001', '是', 1, '是', NULL, '0', 'yorn001', 0, 0, '', 'yorn', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'yorn002', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'yorn002', '否', 1, '否', NULL, '0', 'yorn002', 0, 0, '', 'yorn', NULL);
/**强和弱*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('sors',NULL,NULL,'0',NULL,'0','sors','强和弱',NULL,'强和弱',1,1,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'sors001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'sors001', '强', 1, '强', NULL, '0', 'sors001', 0, 0, '', 'sors', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'sors002', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'sors002', '弱', 1, '弱', NULL, '0', 'sors002', 0, 0, '', 'sors', NULL);
/**涉及业务 {'id':'0','text':'一手楼贷款'},{'id':'1','text':'二手楼贷款'},{'id':'2','text':'个人消费性贷款'},{'id':'3','text':'个人经营性贷款'},{'id':'4','text':'汽车贷款'},{'id':'5','text':'其他'}*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('sjyw',NULL,NULL,'0',NULL,'0','sjyw','涉及业务',NULL,'涉及业务',1,1,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'syjw001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'syjw001', '一手楼贷款', 1, '一手楼贷款', NULL, '0', 'syjw001', 0, 0, '', 'sjyw', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'syjw002', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'syjw002', '二手楼贷款', 1, '二手楼贷款', NULL, '0', 'syjw002', 0, 0, '', 'sjyw', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'syjw003', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'syjw003', '个人消费性贷款', 1, '个人消费性贷款', NULL, '0', 'syjw003', 0, 0, '', 'sjyw', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'syjw004', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'syjw004', '个人经营性贷款', 1, '个人经营性贷款', NULL, '0', 'syjw004', 0, 0, '', 'sjyw', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'syjw005', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'syjw005', '汽车贷款', 1, '汽车贷款', NULL, '0', 'syjw005', 0, 0, '', 'sjyw', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'syjw006', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'syjw006', '其他', 1, '其他', NULL, '0', 'syjw006', 0, 0, '', 'sjyw', NULL);
/**可接受付佣方式 {'id':'0','text':'月结'},{'id':'1','text':'递件'},{'id':'2','text':'放款'},{'id':'3','text':'抵押'},{'id':'4','text':'其他'}*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,
createOrgCd,updateOrgCd)VALUES('fyfs',NULL,NULL,'0',NULL,'0','sjyw','可接受付佣方式',NULL,'可接受付佣方式',1,1,0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`,
`isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`)
VALUES ('0', 'fyfs001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'fyfs001', '月结', 1, '月结', NULL, '0', 'fyfs001', 0, 0, '', 'fyfs', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`,
`isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) 
VALUES ('0', 'fyfs002', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'fyfs002', '递件', 1, '递件', NULL, '0', 'fyfs002', 0, 0, '', 'fyfs', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`,
`isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) 
VALUES ('0', 'fyfs003', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'fyfs003', '放款', 1, '放款', NULL, '0', 'fyfs003', 0, 0, '', 'fyfs', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`,
`isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) 
VALUES ('0', 'fyfs004', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'fyfs004', '抵押', 1, '抵押', NULL, '0', 'fyfs004', 0, 0, '', 'fyfs', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`,
`isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) 
VALUES ('0', 'fyfs005', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'fyfs005', '其他', 1, '其他', NULL, '0', 'fyfs005', 0, 0, '', 'fyfs', NULL);

/**资方类型*/
INSERT INTO ess_codecategory (id,createTime,deleteTime,isDeleted,updateTime,version,categoryCd,categoryNm,codeGenRuler,description,isCommon,isEnabled,isTree,orderNo,createBy,updateBy,createOrgCd,updateOrgCd)VALUES('zflx',NULL,NULL,'0',NULL,'0','zflx','资方类型',NULL,'资方类型',1,1,0,NULL,NULL,NULL,NULL,NULL);

INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zflx001', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'bank', '银行', 1, '银行', NULL, '0', 'bank', 0, 0, '', 'zflx', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zflx002', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'p2p', 'P2P', 1, 'P2P', NULL, '0', 'p2p', 0, 0, '', 'zflx', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zflx003', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'guarantee', '担保', 1, '担保', NULL, '0', 'guarantee', 0, 0, '', 'zflx', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zflx004', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'loan', '小贷', 1, '小贷', NULL, '0', 'loan', 0, 0, '', 'zflx', NULL);
INSERT INTO ess_simplecode (`isTree`, `id`, `createBy`, `createOrgCd`, `createTime`, `deleteTime`, `isDeleted`, `updateBy`, `updateOrgCd`, `updateTime`, `version`, `code`, `desc_`, `isEnable`, `name`, `codeFlag`, `dispOrder`, `fullCode`, `isDefault`, `isFixed`, `sysCode`, `codeCategory_id`, `parent_id`) VALUES ('0', 'zflx005', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', 'trust', '信托', 1, '信托', NULL, '0', 'trust', 0, 0, '', 'zflx', NULL);
